//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset_Serialization.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAuthorization
    {
        public string Identifier { get; set; }
        public string FunctionName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
