//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset_Serialization.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string ActionDesc { get; set; }
        public string Roles { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
