//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset_Serialization.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnsetControlEntities : DbContext
    {
        public OnsetControlEntities()
            : base("name=OnsetControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppAuthorization> AppAuthorizations { get; set; }
        public virtual DbSet<Authorization> Authorizations { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageData> PackageDatas { get; set; }
        public virtual DbSet<PrintLog> PrintLogs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductionOrder> ProductionOrders { get; set; }
        public virtual DbSet<ProductLabel> ProductLabels { get; set; }
        public virtual DbSet<ProductRouter> ProductRouters { get; set; }
        public virtual DbSet<SerialComponent> SerialComponents { get; set; }
        public virtual DbSet<SerialData> SerialDatas { get; set; }
        public virtual DbSet<SerialRouting> SerialRoutings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RouterInput> RouterInputs { get; set; }
    }
}
