//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset_Serialization.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintLog
    {
        public int Id { get; set; }
        public System.Guid RefId { get; set; }
        public string SerialNumber { get; set; }
        public string LabelName { get; set; }
        public string PrintedData { get; set; }
        public string PrintedBy { get; set; }
        public System.DateTime PrintedDate { get; set; }
        public string Machine { get; set; }
    
        public virtual User User { get; set; }
    }
}
